#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
FIXTURE_DIR="$DIR/../fixture"
COMPILED_INK_DIR="$FIXTURE_DIR/compiled"
INK_DIR="$FIXTURE_DIR/original"

for ink_file in $(ls "$INK_DIR"/**/*.ink)
do
    truncated_ink_file=${ink_file#"$INK_DIR"}

    dirname=$(dirname "$truncated_ink_file")
    filename=$(basename "$truncated_ink_file")

    extra_arguments=""
    if [[ "$filename" == "turns_since_with_variable_target.ink" || "$filename" == "read_count_variable_target.ink" || "$filename" == "read_count_variable_target.ink" ]]; then
        extra_arguments="-c"
    fi

    mkdir -p "$COMPILED_INK_DIR/$dirname"
    inklecate $extra_arguments -o "$COMPILED_INK_DIR/$dirname/$filename.json" "$ink_file"

done
